Follow Zeitwerk conventions for file structure
Without this change, we will get a warning when switching to Zeitwerk:

```
NameError: uninitialized constant OmniauthWordpress
```